### ISSUE TITLE
Audio Files For Android App

### ISSUE THREAD

**Issue by aqsashahid123** [islamic-apps/alquran-tools#2]
Assalam o alaikum,
I really liked your effort but i am stuck somewhere in the app.
I am trying to build an android app 
I wanted to ask about the copyrights and stuff
2ndly I can't find any audio file.
From where are you people getting that.

**Comment by meezaan** [comment]
Alaykum Salaam. For audio files, you can use the CDN.

To see a list of all audio, available - http://api.alquran.cloud/edition/format/audio.

Let's say you want to use the ar.alafasy edition. For Surah 2, Ayah 255 (Ayatul Kursi), use http://cdn.alquran.cloud/media/audio/ayah/ar.alafasy/262, where 262 is the ayah number.

Hope this helps.

**Comment by meezaan** [comment]
Oh and for copyrights - there is no human copyright. It's the Qur'an - it belongs to Him and Him alone.

**Comment by aqsashahid123** [comment]
Thank u so so so very much..
May Allah bless u..

**Comment by meezaan** [comment]
Ahlan wa sahlan.

**Comment by noorhossain** [comment]
Jajakullahu Khairan.

Many many thanks For the Audio Information. Is there another link for Audio for another Qari's?
